baseURL: # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: JYJY
paginate: 5
theme: charlolamode

menu:
  main:
    - name: Resume
      url: /resume/
      weight: 30
params:
  author: Jiayin

  hideFooter: true
  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true

  profileMode:
    enabled: true
    title: Hello
    description: |
      I'm Jiayin and I'm a 3D printing enthusiast :)

    imageUrl: "/images/human/me_cropped.jpg"
    imageTitle: my image
    buttons:
      - name: api/getResume
        url: resume/
      - name: api/downloadResume
        url: "/files/resume.pdf"
      - name: api/printer
        url: printer/
  socialIcons:
    - name: github
      url: "https://github.com/lhinjy"
    - name: linkedin
      url: "https://www.linkedin.com/in/huangjiayin-lin/"

  # change favicon in images folder (icon for web tab)
  assets:
    favicon: "/images/favicon/favicon.ico"
    favicon16x16: "/images/favicon/favicon-16x16.png"
    favicon32x32: "/images/favicon/favicon-32x32.png"
    apple_touch_icon: "/images/favicon/apple-touch-icon.png"
    safari_pinned_tab: "/images/favicon/apple-touch-icon.png"
